# Generated by Django 6.0.5 on 2026-06-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lote', models.CharField(max_length=50, unique=True)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('proveedor', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Vencido', 'Vencido'), ('Agotado', 'Agotado')], default='Activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.TextField(help_text='Ej: Compra, Donación, Venta, Merma')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='medicamentos.medicamento')),
            ],
        ),
        migrations.DeleteModel(
            name='Hueco',
        ),
    ]
