# Generated by Django 6.0.4 on 2026-04-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id_agente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(max_length=12, unique=True)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agente.especialidad')),
            ],
        ),
    ]
